<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [

            [
                'usertype' => 'student',
                'name' => 'Rahim Mia',
                'email' => 'rahim.mia@example.com',
                'mobile' => '01715896321',
                'address' => 'Mirpur, Dhaka',
                'gender' => 'male',
                'fname' => 'Abdul Gofur',
                'mname' => 'Rehana Begum',
                'religion' => 'Islam',
                'id_no' => '1998123456',
                'dob' => '1998-05-12',
                'code' => '7542',
                'password' => Hash::make('7542'), // Use Hash::make() in actual seeder
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:00:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Jesmin Akhter',
                'email' => 'jesmin.akhter@example.com',
                'mobile' => '01819654321',
                'address' => 'Khulna Sadar',
                'gender' => 'female',
                'fname' => 'Jamal Uddin',
                'mname' => 'Shahanara Khatun',
                'religion' => 'Islam',
                'id_no' => '2000246802',
                'dob' => '2000-11-25',
                'code' => '4190',
                'password' => Hash::make('4190'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:01:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Shuvo Paul',
                'email' => 'shuvo.paul@example.com',
                'mobile' => '01912345678',
                'address' => 'Narayanganj, Fatullah',
                'gender' => 'male',
                'fname' => 'Bimal Paul',
                'mname' => 'Shanti Rani',
                'religion' => 'Hinduism',
                'id_no' => '1999135791',
                'dob' => '1999-07-03',
                'code' => '1835',
                'password' => Hash::make('1835'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:02:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Moushumi Moni',
                'email' => 'moushumi.moni@example.com',
                'mobile' => '01618765432',
                'address' => 'Barishal, Kotwali',
                'gender' => 'female',
                'fname' => 'Farhad Hossain',
                'mname' => 'Sufia Begum',
                'religion' => 'Islam',
                'id_no' => '2001975310',
                'dob' => '2001-02-14',
                'code' => '9276',
                'password' => Hash::make('9276'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:03:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Rashed Khan',
                'email' => 'rashed.khan@example.com',
                'mobile' => '01511234567',
                'address' => 'Agrabad, Chittagong',
                'gender' => 'male',
                'fname' => 'Abul Kashem',
                'mname' => 'Nurjahan Begum',
                'religion' => 'Islam',
                'id_no' => '1997864201',
                'dob' => '1997-09-08',
                'code' => '5061',
                'password' => Hash::make('5061'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:04:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Nadia Haque',
                'email' => 'nadia.haque@example.com',
                'mobile' => '01711987654',
                'address' => 'Sylhet, Subidbazar',
                'gender' => 'female',
                'fname' => 'Anwarul Haque',
                'mname' => 'Maksuda Khanam',
                'religion' => 'Islam',
                'id_no' => '2002159263',
                'dob' => '2002-04-17',
                'code' => '3409',
                'password' => Hash::make('3409'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:05:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Biplob Das',
                'email' => 'biplob.das@example.com',
                'mobile' => '01614567890',
                'address' => 'Rajshahi, Boalia',
                'gender' => 'male',
                'fname' => 'Sunil Das',
                'mname' => 'Maya Rani',
                'religion' => 'Hinduism',
                'id_no' => '1996248135',
                'dob' => '1996-12-01',
                'code' => '8714',
                'password' => Hash::make('8714'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:06:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Afroza Sultana',
                'email' => 'afroza.sultana@example.com',
                'mobile' => '01918321098',
                'address' => 'Rangpur, Payra Chat',
                'gender' => 'female',
                'fname' => 'Abul Bashar',
                'mname' => 'Halima Begum',
                'religion' => 'Islam',
                'id_no' => '2003704819',
                'dob' => '2003-08-28',
                'code' => '2553',
                'password' => Hash::make('2553'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:07:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Imran Hossain',
                'email' => 'imran.hossain@example.com',
                'mobile' => '01815123456',
                'address' => 'Jessore, Monirampur',
                'gender' => 'male',
                'fname' => 'Sirajul Islam',
                'mname' => 'Saleha Begum',
                'religion' => 'Islam',
                'id_no' => '1995530947',
                'dob' => '1995-03-20',
                'code' => '6931',
                'password' => Hash::make('6931'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:08:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Tasmia Rahman',
                'email' => 'tasmia.rahman@example.com',
                'mobile' => '01514789012',
                'address' => 'Cox\'s Bazar, Teknaf',
                'gender' => 'female',
                'fname' => 'Azizul Haque',
                'mname' => 'Momotaj Begum',
                'religion' => 'Islam',
                'id_no' => '2004481357',
                'dob' => '2004-10-06',
                'code' => '0382',
                'password' => Hash::make('0382'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:09:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Alomgir Hasan',
                'email' => 'alomgir.hasan@example.com',
                'mobile' => '01716345678',
                'address' => 'Mymensingh, Trisal',
                'gender' => 'male',
                'fname' => 'Idris Ali',
                'mname' => 'Amena Khatun',
                'religion' => 'Islam',
                'id_no' => '1998592634',
                'dob' => '1998-01-19',
                'code' => '4725',
                'password' => Hash::make('4725'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:10:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Bristi Chakma',
                'email' => 'bristi.chakma@example.com',
                'mobile' => '01813789012',
                'address' => 'Rangamati Sadar',
                'gender' => 'female',
                'fname' => 'Bijoy Chakma',
                'mname' => 'Ratna Chakma',
                'religion' => 'Buddhism',
                'id_no' => '2000369258',
                'dob' => '2000-06-22',
                'code' => '8169',
                'password' => Hash::make('8169'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:11:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Sayeed Ahmed',
                'email' => 'sayeed.ahmed@example.com',
                'mobile' => '01917123456',
                'address' => 'Comilla, Burichang',
                'gender' => 'male',
                'fname' => 'Shafiqul Islam',
                'mname' => 'Laila Begum',
                'religion' => 'Islam',
                'id_no' => '1999741852',
                'dob' => '1999-04-10',
                'code' => '2904',
                'password' => Hash::make('2904'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:12:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Faria Tabassum',
                'email' => 'faria.tabassum@example.com',
                'mobile' => '01611567890',
                'address' => 'Bogura, Sherpur',
                'gender' => 'female',
                'fname' => 'Monir Hossain',
                'mname' => 'Bilkis Begum',
                'religion' => 'Islam',
                'id_no' => '2001852963',
                'dob' => '2001-12-05',
                'code' => '6347',
                'password' => Hash::make('6347'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:13:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Dipu Roy',
                'email' => 'dipu.roy@example.com',
                'mobile' => '01512345678',
                'address' => 'Dinajpur Sadar',
                'gender' => 'male',
                'fname' => 'Gobinda Roy',
                'mname' => 'Protima Rani',
                'religion' => 'Hinduism',
                'id_no' => '1997369147',
                'dob' => '1997-02-28',
                'code' => '0158',
                'password' => Hash::make('0158'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:14:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Shampa Barua',
                'email' => 'shampa.barua@example.com',
                'mobile' => '01712789012',
                'address' => 'Bandarban Sadar',
                'gender' => 'female',
                'fname' => 'Mangal Barua',
                'mname' => 'Rina Barua',
                'religion' => 'Buddhism',
                'id_no' => '2002147369',
                'dob' => '2002-09-15',
                'code' => '7891',
                'password' => Hash::make('7891'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:15:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Nasir Uddin',
                'email' => 'nasir.uddin@example.com',
                'mobile' => '01816543210',
                'address' => 'Kushtia, Mirpur',
                'gender' => 'male',
                'fname' => 'Abdul Malek',
                'mname' => 'Kulsum Begum',
                'religion' => 'Islam',
                'id_no' => '1996258963',
                'dob' => '1996-05-23',
                'code' => '5520',
                'password' => Hash::make('5520'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:16:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Khadiza Akter',
                'email' => 'khadiza.akter@example.com',
                'mobile' => '01911901234',
                'address' => 'Gazipur, Tongi',
                'gender' => 'female',
                'fname' => 'Abu Taher',
                'mname' => 'Sufia Begum',
                'religion' => 'Islam',
                'id_no' => '2003852741',
                'dob' => '2003-11-09',
                'code' => '3602',
                'password' => Hash::make('3602'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:17:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Joynal Abedin',
                'email' => 'joynal.abedin@example.com',
                'mobile' => '01619876543',
                'address' => 'Sylhet, Balaganj',
                'gender' => 'male',
                'fname' => 'Aftab Uddin',
                'mname' => 'Jamila Begum',
                'religion' => 'Islam',
                'id_no' => '1995963852',
                'dob' => '1995-08-04',
                'code' => '9073',
                'password' => Hash::make('9073'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:18:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Samia Afrin',
                'email' => 'samia.afrin@example.com',
                'mobile' => '01519210987',
                'address' => 'Rangpur, Mithapukur',
                'gender' => 'female',
                'fname' => 'Harun Rashid',
                'mname' => 'Farida Khatun',
                'religion' => 'Islam',
                'id_no' => '2004147258',
                'dob' => '2004-03-29',
                'code' => '1246',
                'password' => Hash::make('1246'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:19:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Atikur Rahman',
                'email' => 'atikur.rahman@example.com',
                'mobile' => '01713456789',
                'address' => 'Savar, Ashulia',
                'gender' => 'male',
                'fname' => 'Mozammel Haque',
                'mname' => 'Khadija Begum',
                'religion' => 'Islam',
                'id_no' => '1998632589',
                'dob' => '1998-10-07',
                'code' => '7850',
                'password' => Hash::make('7850'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:20:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Lima Akter',
                'email' => 'lima.akter@example.com',
                'mobile' => '01811567890',
                'address' => 'Barishal, Bakerganj',
                'gender' => 'female',
                'fname' => 'Shahjahan Ali',
                'mname' => 'Rokeya Begum',
                'religion' => 'Islam',
                'id_no' => '2000258741',
                'dob' => '2000-01-21',
                'code' => '4931',
                'password' => Hash::make('4931'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:21:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Polash Biswas',
                'email' => 'polash.biswas@example.com',
                'mobile' => '01915345678',
                'address' => 'Jessore Sadar',
                'gender' => 'male',
                'fname' => 'Nitai Biswas',
                'mname' => 'Shoma Rani',
                'religion' => 'Hinduism',
                'id_no' => '1999963214',
                'dob' => '1999-06-16',
                'code' => '8274',
                'password' => Hash::make('8274'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:22:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Maria Jannat',
                'email' => 'maria.jannat@example.com',
                'mobile' => '01617901234',
                'address' => 'Chittagong, Halishahar',
                'gender' => 'female',
                'fname' => 'Delwar Hossain',
                'mname' => 'Nasrin Akter',
                'religion' => 'Islam',
                'id_no' => '2001589632',
                'dob' => '2001-09-30',
                'code' => '0017',
                'password' => Hash::make('0017'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:23:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Shahriar Alam',
                'email' => 'shahriar.alam@example.com',
                'mobile' => '01517567890',
                'address' => 'Narail Sadar',
                'gender' => 'male',
                'fname' => 'Golam Mostofa',
                'mname' => 'Shapna Begum',
                'religion' => 'Islam',
                'id_no' => '1997123987',
                'dob' => '1997-04-05',
                'code' => '6489',
                'password' => Hash::make('6489'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:24:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Mitu Debnath',
                'email' => 'mitu.debnath@example.com',
                'mobile' => '01718321098',
                'address' => 'Sylhet, Sunamganj',
                'gender' => 'female',
                'fname' => 'Shudhir Debnath',
                'mname' => 'Priti Rani',
                'religion' => 'Hinduism',
                'id_no' => '2002369852',
                'dob' => '2002-07-13',
                'code' => '5362',
                'password' => Hash::make('5362'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:25:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Shafiqul Islam',
                'email' => 'shafiqul.islam@example.com',
                'mobile' => '01814789012',
                'address' => 'Natore Sadar',
                'gender' => 'male',
                'fname' => 'Fazlul Haque',
                'mname' => 'Rokeya Khatun',
                'religion' => 'Islam',
                'id_no' => '1996741258',
                'dob' => '1996-03-18',
                'code' => '9105',
                'password' => Hash::make('9105'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:26:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Rumana Afroz',
                'email' => 'rumana.afroz@example.com',
                'mobile' => '01914567890',
                'address' => 'Pirojpur Sadar',
                'gender' => 'female',
                'fname' => 'Abdul Kader',
                'mname' => 'Momtaz Begum',
                'religion' => 'Islam',
                'id_no' => '2003852147',
                'dob' => '2003-05-02',
                'code' => '3749',
                'password' => Hash::make('3749'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:27:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Anisul Haque',
                'email' => 'anisul.haque@example.com',
                'mobile' => '01613123456',
                'address' => 'Kishoreganj, Bhairab',
                'gender' => 'male',
                'fname' => 'Nurul Islam',
                'mname' => 'Asma Begum',
                'religion' => 'Islam',
                'id_no' => '1995478963',
                'dob' => '1995-11-26',
                'code' => '0628',
                'password' => Hash::make('0628'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:28:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Trisha Roy',
                'email' => 'trisha.roy@example.com',
                'mobile' => '01516789012',
                'address' => 'Thakurgaon Sadar',
                'gender' => 'female',
                'fname' => 'Biren Roy',
                'mname' => 'Bimala Rani',
                'religion' => 'Hinduism',
                'id_no' => '2004258963',
                'dob' => '2004-08-11',
                'code' => '2851',
                'password' => Hash::make('2851'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:29:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Kamrul Hasan',
                'email' => 'kamrul.hasan@example.com',
                'mobile' => '01714876543',
                'address' => 'Pabna, Ishwardi',
                'gender' => 'male',
                'fname' => 'Mokbul Hossain',
                'mname' => 'Mariam Begum',
                'religion' => 'Islam',
                'id_no' => '1998741852',
                'dob' => '1998-03-09',
                'code' => '8936',
                'password' => Hash::make('8936'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:30:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Shathi Das',
                'email' => 'shathi.das@example.com',
                'mobile' => '01817345678',
                'address' => 'Satkhira Sadar',
                'gender' => 'female',
                'fname' => 'Babul Das',
                'mname' => 'Anjali Rani',
                'religion' => 'Hinduism',
                'id_no' => '2000369852',
                'dob' => '2000-04-14',
                'code' => '4370',
                'password' => Hash::make('4370'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:31:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Jasim Uddin',
                'email' => 'jasim.uddin@example.com',
                'mobile' => '01913789012',
                'address' => 'Gazipur, Kaliakoir',
                'gender' => 'male',
                'fname' => 'Abdul Mannan',
                'mname' => 'Shamsun Nahar',
                'religion' => 'Islam',
                'id_no' => '1999123478',
                'dob' => '1999-09-27',
                'code' => '6712',
                'password' => Hash::make('6712'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:32:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Nusrat Jahan',
                'email' => 'nusrat.jahan@example.com',
                'mobile' => '01616543210',
                'address' => 'Munshiganj Sadar',
                'gender' => 'female',
                'fname' => 'Tofazzal Hossain',
                'mname' => 'Saleha Begum',
                'religion' => 'Islam',
                'id_no' => '2001963214',
                'dob' => '2001-06-08',
                'code' => '0864',
                'password' => Hash::make('0864'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:33:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Raihan Sharif',
                'email' => 'raihan.sharif@example.com',
                'mobile' => '01518123456',
                'address' => 'Magura Sadar',
                'gender' => 'male',
                'fname' => 'Fazlul Karim',
                'mname' => 'Amina Begum',
                'religion' => 'Islam',
                'id_no' => '1997369147',
                'dob' => '1997-12-25',
                'code' => '2197',
                'password' => Hash::make('2197'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:34:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Priya Chakroborty',
                'email' => 'priya.chakroborty@example.com',
                'mobile' => '01717678901',
                'address' => 'Moulvibazar Sadar',
                'gender' => 'female',
                'fname' => 'Proshanto Chakroborty',
                'mname' => 'Shipra Rani',
                'religion' => 'Hinduism',
                'id_no' => '2002741852',
                'dob' => '2002-10-31',
                'code' => '5403',
                'password' => Hash::make('5403'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:35:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Mostofa Kamal',
                'email' => 'mostofa.kamal@example.com',
                'mobile' => '01818234567',
                'address' => 'Noakhali Sadar',
                'gender' => 'male',
                'fname' => 'Sayed Ali',
                'mname' => 'Momena Begum',
                'religion' => 'Islam',
                'id_no' => '1996589632',
                'dob' => '1996-08-14',
                'code' => '9825',
                'password' => Hash::make('9825'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:36:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Sanjida Islam',
                'email' => 'sanjida.islam@example.com',
                'mobile' => '01916901234',
                'address' => 'Feni Sadar',
                'gender' => 'female',
                'fname' => 'Rafiqul Islam',
                'mname' => 'Halima Khatun',
                'religion' => 'Islam',
                'id_no' => '2003147369',
                'dob' => '2003-06-01',
                'code' => '1048',
                'password' => Hash::make('1048'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:37:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Tanvir Hasan',
                'email' => 'tanvir.hasan@example.com',
                'mobile' => '01615789012',
                'address' => 'Khulna, Daulatpur',
                'gender' => 'male',
                'fname' => 'Abul Hossain',
                'mname' => 'Shamsunnahar',
                'religion' => 'Islam',
                'id_no' => '1995369852',
                'dob' => '1995-01-17',
                'code' => '7631',
                'password' => Hash::make('7631'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:38:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Sumiya Akter',
                'email' => 'sumiya.akter@example.com',
                'mobile' => '01513210987',
                'address' => 'Dhaka, Jatrabari',
                'gender' => 'female',
                'fname' => 'Ibrahim Khalil',
                'mname' => 'Khairun Nahar',
                'religion' => 'Islam',
                'id_no' => '2004963852',
                'dob' => '2004-12-29',
                'code' => '4259',
                'password' => Hash::make('4259'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:39:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Abdur Rouf',
                'email' => 'abdur.rouf@example.com',
                'mobile' => '01719543210',
                'address' => 'Bogura, Sariakandi',
                'gender' => 'male',
                'fname' => 'Amzad Hossain',
                'mname' => 'Rahela Begum',
                'religion' => 'Islam',
                'id_no' => '1998478521',
                'dob' => '1998-07-24',
                'code' => '8806',
                'password' => Hash::make('8806'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:40:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Mitu Akter',
                'email' => 'mitu.akter@example.com',
                'mobile' => '01812876543',
                'address' => 'Tangail Sadar',
                'gender' => 'female',
                'fname' => 'Abdul Aziz',
                'mname' => 'Sufiya Begum',
                'religion' => 'Islam',
                'id_no' => '2000589632',
                'dob' => '2000-09-03',
                'code' => '0513',
                'password' => Hash::make('0513'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:41:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Babul Hossain',
                'email' => 'babul.hossain@example.com',
                'mobile' => '01919654321',
                'address' => 'Rajshahi, Puthia',
                'gender' => 'male',
                'fname' => 'Monir Uddin',
                'mname' => 'Jamila Khatun',
                'religion' => 'Islam',
                'id_no' => '1999258963',
                'dob' => '1999-02-06',
                'code' => '6194',
                'password' => Hash::make('6194'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:42:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Farzana Yasmin',
                'email' => 'farzana.yasmin@example.com',
                'mobile' => '01612789012',
                'address' => 'Gopalganj Sadar',
                'gender' => 'female',
                'fname' => 'Abdur Rashid',
                'mname' => 'Morzina Begum',
                'religion' => 'Islam',
                'id_no' => '2001147369',
                'dob' => '2001-04-12',
                'code' => '3980',
                'password' => Hash::make('3980'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:43:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Nadim Hasan',
                'email' => 'nadim.hasan@example.com',
                'mobile' => '01515432109',
                'address' => 'Patuakhali Sadar',
                'gender' => 'male',
                'fname' => 'Motaleb Hossain',
                'mname' => 'Khadiza Akter',
                'religion' => 'Islam',
                'id_no' => '1997963852',
                'dob' => '1997-06-20',
                'code' => '5678',
                'password' => Hash::make('5678'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:44:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Shanta Rani',
                'email' => 'shanta.rani@example.com',
                'mobile' => '01710987654',
                'address' => 'Khulna, Dumuria',
                'gender' => 'female',
                'fname' => 'Shibu Lal',
                'mname' => 'Purnima Rani',
                'religion' => 'Hinduism',
                'id_no' => '2002369852',
                'dob' => '2002-03-26',
                'code' => '9401',
                'password' => Hash::make('9401'),
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:45:00',
            ],
            [
                'usertype' => 'student',
                'name' => 'Arafat Zaman',
                'email' => 'arafat.zaman@example.com',
                'mobile' => '01810654321',
                'address' => 'Cumilla, Chandina',
                'gender' => 'male',
                'fname' => 'Abdul Jalil',
                'mname' => 'Rizia Begum',
                'religion' => 'Islam',
                'id_no' => '1996589632',
                'dob' => '1996-10-01', // Completed missing date
                'code' => '3519', // Added a new unique code
                'password' => Hash::make('3519'), // Hashed password for the new code
                'role' => 'student',
                'status' => 1,
                'created_at' => '2025-01-10 10:46:00', // Added a new created_at timestamp
            ],
            [
                'usertype' => 'admin',
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'mobile' => '01873593399',
                'address' => 'Rangpur',
                'gender' => 'male',
                'fname' => 'Abdur Razzak',
                'mname' => 'Masuda Begum',
                'religion' => 'Islam',
                'id_no' => '1996589632',
                'dob' => '2002-05-23', // Completed missing date
                'code' => '111', // Added a new unique code
                'password' => Hash::make('111'), // Hashed password for the new code
                'role' => 'admin',
                'status' => 1,
                'created_at' => '2025-01-10 10:46:00', // Added a new created_at timestamp
            ],
            [
                'usertype' => 'teacher',
                'name' => 'Teacher',
                'email' => 'teacher@gmail.com',
                'mobile' => '01893593399',
                'address' => 'Rangpur',
                'gender' => 'male',
                'fname' => 'Abdur Razzak',
                'mname' => 'Masuda Begum',
                'religion' => 'Islam',
                'id_no' => '1887589632',
                'dob' => '2002-05-23', // Completed missing date
                'code' => '111', // Added a new unique code
                'password' => Hash::make('111'), // Hashed password for the new code
                'role' => 'teacher',
                'status' => 1,
                'created_at' => '2025-01-10 10:46:00', // Added a new created_at timestamp
            ],
        ];

        DB::table('users')->insert($users);
    }
}
